### ISSUE TITLE
'Price' 0.00 in FlexOrder not considered to match 0.0 in FlexOffer

### ISSUE THREAD

**Issue by tomwetjens** [shapeshifter/shapeshifter-library-java#37]
FlexOffer.Price = 0.00

FlexOrder.Price=0.0

This leads to a validation error that Price should be equal.

The UFTP specification says ISO 4217 should be used. This specifies the number of decimals depending on the currency.

Proposal:

- Change FlexOrderPriceMatchValidator to consider two Price values equal regardless of scale.
- Add new validator to check the Price value
- For extra robustness: it should at most N decimals (depending on the currency, 3 for EUR)

**Comment by MartenMeijboom98** [comment]
Fixed in https://github.com/shapeshifter/shapeshifter-library/pull/38

**Comment by Christiaan-Kornaat-edsn** [comment]
The link to the merge request: https://github.com/shapeshifter/shapeshifter-library/pull/38
