### ISSUE TITLE
HTTP redirects (3xx status codes) are not honoured

### ISSUE THREAD

**Issue by tomwetjens** [shapeshifter/shapeshifter-library-java#55]
From the Shapeshifter specification: "when using HTTP version 1.1, redirects (responses with status code 3xx) should be honored in order to support load balancing. "

Currently the Java library does not honour the 3xx status codes and throws an exception instead.

302, 307 status codes should be implemented so that the request is retried against the URL in the Location header.
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307
Also:  HTTP 308 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308

303 should not be honoured as it changes the method to GET which is not compliant. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303 

301 could be implemented similar to 302 and 307.

Implementation notes:
- Probably need to change UftpSendMessageService
- Throw exception if no Location header available
- Don't follow redirects infinitely: let's set a max amount of redirects to follow for one initial request

**Comment by MartenMeijboom98** [comment]
Do we also need to honour HTTP 308? https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308
