### ISSUE TITLE
Add validation that referenced FlexRequest and FlexOffer are in the same conversation

### ISSUE THREAD

**Issue by MartenMeijboom98** [shapeshifter/shapeshifter-library-java#61]
FlexRequest referenced by a FlexOrder and FlexOffer referenced by a FlexOrder must be part of the same conversation! Else it must be rejected.

FlexRequest: MessageID=RE1 ConversationID=C1

FlexOffer: MessageID=OF1 FlexRequestMessageID=RE1 ConversationID=C2 → must be REJECTED (actual: ACCEPTED)

FlexOrder: FlexOfferMessageID=OF1 ConversationID=C3 → must be REJECTED (actual: ACCEPTED)

**Comment by eelcodenheijer** [comment]
Implemented by https://github.com/shapeshifter/shapeshifter-library-java/pull/62
